[package]
name = "cprs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.88"
confy = "0.6.1"
crossterm = "0.28.1"
dirs = "5.0.1"
log = "0.4.22"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
